### ISSUE TITLE
Don't steal peoples scripts and call them your own lmfao

### ISSUE THREAD

**Issue by GazTheTaz6385** [varTapexe/EdgenuityHack#1]
Assignment unlocker was made by subatomic mc and I think a few other are miss attributed too

**Comment by varTapexe** [comment]
I didn’t steal anything. I found a hack on GitHub and I improved upon it and fixed a few bugs.

I’m not selling it either it’s all free on the site.

**Comment by varTapexe** [comment]
Thank you for your feedback.
